// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haxjenuqrzyzmrswkzbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheGplbnVxcnp5em1yc3dremJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjMxNDMsImV4cCI6MjA3MDM5OTE0M30.MtyZ3s3ikN-JmsATXqiokxVLVeGwzNVqL1Uavpf3ars";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});